# Generated by Django 3.1.7 on 2021-04-04 20:19

import createfolder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('I', 'B.Tech 1'), ('II', 'B.Tech 2')], default='I', max_length=100)),
                ('branch', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=10)),
                ('excel_sheet', models.FileField(upload_to=createfolder.models.get_file_path)),
            ],
        ),
    ]
