# Generated by Django 3.1.7 on 2021-04-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createfolder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='year',
            field=models.CharField(choices=[('I', 'B.Tech 1'), ('II', 'B.Tech 2'), ('III', 'B.Tech 3'), ('IV', 'B.Tech 4')], default='I', max_length=100),
        ),
    ]
