# Generated by Django 3.1.7 on 2021-04-07 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_auto_20210406_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_control_list', to='authentication.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='subjectcontrol/files')),
                ('subject_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_files_list', to='subjectcontrol.subjectcontrol')),
            ],
        ),
    ]
