# Generated by Django 3.1.7 on 2021-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfiles',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
