# Generated by Django 3.1.7 on 2021-04-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210406_2300'),
        ('subjectcontrol', '0002_subjectfiles_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectControl',
            new_name='Notes',
        ),
        migrations.RenameModel(
            old_name='SubjectFiles',
            new_name='NotesFiles',
        ),
    ]
