# Generated by Django 3.1.7 on 2021-04-04 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='profilepics')),
                ('designation', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('year', models.CharField(choices=[('-', '-'), ('B.tech I year', 'B.tech I year'), ('B.tech II year', 'B.tech II year'), ('B.tech III year', 'B.tech III year'), ('B.tech IV year', 'B.tech IV year')], default='-', max_length=100)),
                ('gender', models.CharField(choices=[('-', '-'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='-', max_length=100)),
                ('dateofbirth', models.DateField()),
                ('fathername', models.CharField(max_length=100)),
                ('fatherphone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
