# Generated by Django 3.1.7 on 2021-04-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subject',
            field=models.CharField(default='PFSD', max_length=200),
            preserve_default=False,
        ),
    ]
